"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { ContentData, PortfolioCase, ShowcaseVersion } from "@/lib/types";

function move<T>(items:T[],from:number,to:number){const next=[...items];const [item]=next.splice(from,1);next.splice(to,0,item);return next}
function VersionEditor({version,cases,onSaved}:{version:ShowcaseVersion;cases:PortfolioCase[];onSaved:(oldSlug:string,next:ShowcaseVersion)=>void}){
  const [draft,setDraft]=useState(version);const [dragged,setDragged]=useState<number|null>(null);const [message,setMessage]=useState("");
  const available=cases.filter((item)=>!draft.priorityCaseIds.includes(item.id));
  async function save(){const response=await fetch(`/api/admin/versions/${version.slug}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(draft)});const body=await response.json();setMessage(response.ok?"已保存":body.error);if(response.ok)onSaved(version.slug,body)}
  return <details className="versionCard"><summary><span>{draft.name}</span><code>/{draft.slug}</code><b>{draft.priorityCaseIds.length} 个优先案例</b></summary><div className="versionFields"><label>名称<input value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></label><label>Slug<input value={draft.slug} onChange={(e)=>setDraft({...draft,slug:e.target.value})}/></label><label className="checkLabel"><input type="checkbox" checked={draft.enabled} onChange={(e)=>setDraft({...draft,enabled:e.target.checked})}/> 启用</label></div><div className="priorityAdd"><select defaultValue="" onChange={(e)=>{if(e.target.value)setDraft({...draft,priorityCaseIds:[...draft.priorityCaseIds,e.target.value]});e.target.value=""}}><option value="">增加优先案例…</option>{available.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><ol className="priorityList">{draft.priorityCaseIds.map((id,index)=>{const item=cases.find((entry)=>entry.id===id);if(!item)return null;return <li key={id} draggable onDragStart={()=>setDragged(index)} onDragOver={(e)=>e.preventDefault()} onDrop={()=>{if(dragged!==null)setDraft({...draft,priorityCaseIds:move(draft.priorityCaseIds,dragged,index)});setDragged(null)}}><span className="dragHandle">⠿</span><span>{item.name}</span><div><button disabled={index===0} onClick={()=>setDraft({...draft,priorityCaseIds:move(draft.priorityCaseIds,index,index-1)})}>↑</button><button disabled={index===draft.priorityCaseIds.length-1} onClick={()=>setDraft({...draft,priorityCaseIds:move(draft.priorityCaseIds,index,index+1)})}>↓</button><button className="dangerText" onClick={()=>setDraft({...draft,priorityCaseIds:draft.priorityCaseIds.filter((entry)=>entry!==id)})}>移除</button></div></li>})}</ol><div className="saveRow"><button className="primaryButton" onClick={save}>保存版本</button><span>{message}</span></div></details>
}
export function AdminDashboard({initial}:{initial:ContentData}){
  const [data,setData]=useState(initial);const [order,setOrder]=useState(initial.defaultOrder);const [dragged,setDragged]=useState<number|null>(null);const [message,setMessage]=useState("");const router=useRouter();
  const ordered=useMemo(()=>order.map((id)=>data.cases.find((item)=>item.id===id)).filter(Boolean) as PortfolioCase[],[order,data.cases]);
  async function saveOrder(){const response=await fetch('/api/admin/order',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({order})});setMessage(response.ok?'默认排序已保存':'保存失败')}
  async function toggle(item:PortfolioCase){const response=await fetch(`/api/admin/cases/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...item,published:!item.published})});if(response.ok)setData({...data,cases:data.cases.map((entry)=>entry.id===item.id?{...entry,published:!entry.published}:entry)})}
  async function remove(item:PortfolioCase){if(!confirm(`确认删除“${item.name}”？媒体文件将保留。`))return;const response=await fetch(`/api/admin/cases/${item.id}`,{method:'DELETE'});if(response.ok){setData({...data,cases:data.cases.filter((entry)=>entry.id!==item.id)});setOrder(order.filter((id)=>id!==item.id))}}
  useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'list_portfolio_cases',title:'列出案例',description:'读取后台中的案例名称、发布状态与默认顺序。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({cases:ordered.map(({id,name,slug,published})=>({id,name,slug,published}))})},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[ordered]);
  return <main className="adminPage"><section className="adminTitle"><div><p>Content / Cases</p><h1>案例管理</h1></div><Link className="primaryButton" href="/admin/cases/new">新建案例</Link></section><section className="adminSection"><div className="sectionHeading"><div><h2>默认首页</h2><p>拖动卡片调整顺序；手机上可使用上下按钮。</p></div><div><button className="primaryButton" onClick={saveOrder}>保存排序</button><span className="saveMessage">{message}</span></div></div><div className="adminCaseList">{ordered.map((item,index)=><article key={item.id} draggable onDragStart={()=>setDragged(index)} onDragOver={(e)=>e.preventDefault()} onDrop={()=>{if(dragged!==null)setOrder(move(order,dragged,index));setDragged(null)}}><span className="dragHandle">⠿</span><div className="adminThumb"><Image src={item.cover} alt="" fill sizes="100px"/></div><div className="adminCaseName"><strong>{item.name}</strong><span>{item.industryPrimary} · {item.designPrimary}</span></div><button className={`status ${item.published?'published':''}`} onClick={()=>toggle(item)}>{item.published?'已发布':'草稿'}</button><div className="mobileReorder"><button disabled={index===0} onClick={()=>setOrder(move(order,index,index-1))}>↑</button><button disabled={index===order.length-1} onClick={()=>setOrder(move(order,index,index+1))}>↓</button></div><Link href={`/admin/cases/${item.id}`}>编辑</Link><button className="dangerText" onClick={()=>remove(item)}>删除</button></article>)}</div></section><section className="adminSection versionsSection"><div className="sectionHeading"><div><h2>定向版本</h2><p>版本只保存优先案例，其余案例自动沿用默认顺序。</p></div></div>{data.versions.map((version)=><VersionEditor key={version.slug} version={version} cases={data.cases} onSaved={(oldSlug,next)=>{setData({...data,versions:data.versions.map((item)=>item.slug===oldSlug?next:item)});router.refresh()}}/>)}</section></main>
}
